updated deploy

diff --git a/bin/.kic/commands/cluster/deploy b/bin/.kic/commands/cluster/deploy
--- a/bin/.kic/commands/cluster/deploy
+++ b/bin/.kic/commands/cluster/deploy
@@ -9,7 +9,7 @@
 # validate directories
 if [ ! -d ./deploy ]; then echo "./deploy directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d ./deploy/webv ]; then echo "./deploy/webv directory not found. Please cd to an appropriate directory"; exit 1; fi
-if [ ! -d ./deploy/csapp ]; then echo "./deploy/csapp directory not found. Please cd to an appropriate directory"; exit 1; fi
+if [ ! -d ./deploy/app ]; then echo "./deploy/app directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d ./deploy/bootstrap ]; then echo "./deploy/bootstrap directory not found. Please cd to an appropriate directory"; exit 1; fi
 
 # build the app
@@ -19,8 +19,8 @@ if [ ! -d ./deploy/bootstrap ]; then echo "./deploy/bootstrap directory not foun
 kubectl apply -f deploy
 kubectl apply -f deploy/bootstrap
 
-# deploy csapp reference app
-kubectl apply -f deploy/csapp
+# deploy app reference app
+kubectl apply -f deploy/app
 
 # deploy prometheus, grafana, and fluent bit
 kubectl apply -R -f deploy/bootstrap
